[gamevals.tables]
mining_enhancers=1218
mining_pickaxes=1219
mining_rocks=1220

[gamevals.dbrows]
mining_enhancers_guardian_remains=96570
mining_enhancers_clay=96571
mining_enhancers_copper=96572
mining_enhancers_tin=96573
mining_enhancers_tephra=96575
mining_enhancers_blurite=96576
mining_enhancers_limestone=96577
mining_enhancers_iron=96578
mining_enhancers_silver=96579
mining_enhancers_lead=96580
mining_enhancers_coal=96581
mining_enhancers_sandstone=96582
mining_enhancers_gold=96583
mining_enhancers_volcanic_sulphur=96584
mining_enhancers_granite=96585
mining_enhancers_mithril=96586
mining_enhancers_lovakite=96587
mining_enhancers_amalgamation=96588
mining_enhancers_adamantite=96589
mining_enhancers_soft_clay=96590
mining_enhancers_nickel=96591
mining_enhancers_runite=96592
mining_enhancers_amethyst=96593
mining_essence=96594
mining_amethystrock=96595
mining_runiterock=96596
mining_adamantiterock=96597
mining_mithrilrock=96598
mining_goldrock=96599
mining_gemrock=96600
mining_clayrock=96601
mining_copperrock=96602
mining_tinrock=96603
mining_bluriterock=96604
mining_ironrock=96605
mining_silverrock=96606
mining_coalrock=96607
mining_bronze_pickaxe=96615
mining_iron_pickaxe=96616
mining_steel_pickaxe=96617
mining_black_pickaxe=96618
mining_mithril_pickaxe=96619
mining_adamant_pickaxe=96620
mining_rune_pickaxe=96621
mining_dragon_pickaxe=96623
mining_3a_pickaxe=96624
mining_infernal_pickaxe=96625
mining_crystal_pickaxe=96626
mining_lovakiterock=982011
mining_nickelrock=982012
mining_leadrock=982013