[gamevals.tables]
teleport_tablets=1227

[gamevals.dbrows]
varrock_teleport_tablet=96967
lumbridge_teleport_tablet=96968
falador_teleport_tablet=96969
camelot_teleport_tablet=96970
kourend_castle_teleport_tablet=96971
ardougne_teleport_tablet=96972
civitas_illa_fortis_teleport_tablet=96973
watchtower_teleport_tablet=96974
arceuus_library_teleport_tablet=96975
draynor_manor_teleport_tablet=96976
battlefront_teleport_tablet=96977
mind_altar_teleport_tablet=96978
salve_graveyard_teleport_tablet=96979
fenkenstrains_castle_teleport_tablet=96980
west_ardougne_teleport_tablet=96981
harmony_island_teleport_tablet=96982
cemetery_teleport_tablet=96983
barrows_teleport_tablet=96984
ape_atoll_teleport_tablet=96985
paddewwa_teleport_tablet=96986
senntisten_teleport_tablet=96987
kharyrll_teleport_tablet=96988
lassar_teleport_tablet=96989
dareeyak_teleport_tablet=96990
carrallanger_teleport_tablet=96991
annakarl_teleport_tablet=96992
ghorrock_teleport_tablet=96993
moonclan_teleport_tablet=96994
ourania_teleport_tablet=96995
waterbirth_teleport_tablet=96996
barbarian_teleport_tablet=96997
khazard_teleport_tablet=96998
fishing_guild_teleport_tablet=96999
catherby_teleport_tablet=97000
ice_plateau_teleport_tablet=97001