[gamevals.tables]
consumable_food=1224

[gamevals.dbrows]
premade_choc_bomb_food=97097
shrimps_food=98030
cooked_chicken_food=98031
cooked_meat_food=98032
bread_food=98033
herring_food=98034
mackerel_food=98035
trout_food=98036
pike_food=98037
peach_food=98038
salmon_food=98039
tuna_food=98040
jug_of_wine_food=98041
lobster_food=98042
bass_food=98043
swordfish_food=98044
ixcoztic_white_food=98045
potato_with_cheese_food=98046
monkfish_food=98047
curry_food=98048
cooked_pyre_fox_food=98049
shark_food=98050
sea_turtle_food=98051
manta_ray_food=98052
tuna_potato_food=98053
dark_crab_food=98054
anglerfish_food=98055
onion_food=98056
cake_food=98057
chocolate_cake_food=98058
redberry_pie_food=98059
meat_pie_food=98060
garden_pie_food=98061
fish_pie_food=98062
apple_pie_food=98063
botanical_pie_food=98064
mushroom_pie_food=98065
admiral_pie_food=98066
plain_pizza_food=98067
meat_pizza_food=98068
anchovy_pizza_food=98069
dragonfruit_pie_food=98070
pineapple_pizza_food=98071
wild_pie_food=98072
summer_pie_food=98073
toad_crunchies_food=98074
premade_td_crunch_food=98075
spicy_crunchies_food=98076
premade_sy_crunch_food=98077
worm_crunchies_food=98078
premade_wm_crun_food=98079
chocchip_crunchies_food=98080
premade_ch_crunch_food=98081
fruit_batta_food=98082
premade_frt_batta_food=98083
toad_batta_food=98084
premade_td_batta_food=98085
worm_batta_food=98086
premade_wm_batta_food=98087
vegetable_batta_food=98088
premade_veg_batta_food=98089
cheese_tom_batta_food=98090
premade_ct_batta_food=98091
worm_hole_food=98092
premade_worm_hole_food=98093
veg_ball_food=98094
premade_veg_ball_food=98095
chocolate_bomb_food=98096
tangled_toads_legs_food=98098
premade_ttl_food=98099
toads_legs_food=98100
crystal_paddlefish_food=98101
corrupted_paddlefish_food=98102
cooked_karambwan_food=98103
blighted_karambwan_food=98104
blighted_manta_ray_food=98105
blighted_anglerfish_food=98106
sweets_food=98107
moonlight_mead_food=98108