[versions]
fastutil = "8.2.1"
sparkCore = "2.3"
kotlinStdlibJdk8 = "1.8.20-RC2"
kotlinLogging = "5.1.0"
jacksonDataformatToml = "2.13.0"
jacksonDatabind = "2.13.0"
json = "20220320"
jbcrypt = "0.4"
gson = "_"
kotlinxSerializationCore = "_"
mongo = "5.1.2"
junit = "4.+"
kotlinTestJunit = "_"
kotlin = "2.0.20"
ksp = "2.0.20-1.0.24"
nettyAll = "4.1.109.Final"
csv = "0.7.3"
logback = "1.4.11"
rsprot = "1.0.0-ALPHA-20251027"
routefinder = "6.0.0"
or2 = "3.0"
or2ServerUtils = "0.7"
jodatime = "2.14.0"
classgraph = "4.8.184"

[libraries]
fastutil = { group = "it.unimi.dsi", name = "fastutil", version.ref = "fastutil" }
spark-core = { group = "com.sparkjava", name = "spark-core", version.ref = "sparkCore" }
kotlin-stdlib-jdk8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlinStdlibJdk8" }


kotlin-scripting = {group = "org.jetbrains.kotlin", name = "kotlin-scripting-common", version = "_"}
kotlin-script-runtime = { group = "org.jetbrains.kotlin", name = "kotlin-script-runtime", version.ref = "kotlin"}

kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version.ref = "kotlinLogging" }
jackson-dataformat-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version = "2.14.2" }
jackson-dataformat-toml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-toml", version.ref = "jacksonDataformatToml" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jacksonDatabind" }
jackson-module-kotlin = {group ="com.fasterxml.jackson.module" , name = "jackson-module-kotlin", version = "2.13.0" }
json = { group = "org.json", name = "json", version.ref = "json" }
reflection = {group = "org.reflections", name = "reflections", version = "_"}
jbcrypt = { group = "org.mindrot", name = "jbcrypt", version.ref = "jbcrypt" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
kotlinx-coroutines = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "_"}
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }
commons = { group = "commons-io", name = "commons-io", version = "_"}
bouncycastle = { group = "org.bouncycastle", name =  "bcprov-jdk15on",version = "_"}
classgraph = { group = "io.github.classgraph", name = "classgraph", version.ref = "classgraph"}
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlinTestJunit"}
kotlin-csv = { group = "com.github.doyaaaaaken", name = "kotlin-csv", version.ref = "csv"}

netty-all = { group = "io.netty", name = "netty-all", version.ref = "nettyAll" }

logback-classic = { group ="ch.qos.logback", name = "logback-classic", version.ref = "logback"}
rsprot = { group = "net.rsprot", name = "osrs-235-api", version.ref = "rsprot"}
routefinder = { group = "org.rsmod", name = "rsmod-routefinder", version.ref = "routefinder"}

mongo-bson = { group = "org.mongodb", name = "bson", version.ref = "mongo"}
mongo-driver = { group = "org.mongodb", name = "mongodb-driver-sync", version.ref = "mongo"}

# Additional libraries migrated to catalog
or2-all-cache = { group = "dev.or2", name = "all", version.ref = "or2" }
or2-tools = { group = "dev.or2", name = "tools", version.ref = "or2" }
or2-server-utils = { group = "dev.or2", name = "server-utils", version.ref = "or2ServerUtils" }
joda-time = { group = "joda-time", name = "joda-time", version.ref = "jodatime" }
or2-definition = { group = "dev.or2", name = "definition", version.ref = "or2" }
or2-filesystem = { group = "dev.or2", name = "filesystem", version.ref = "or2" }
or2-filestore = { group = "dev.or2", name = "filestore", version.ref = "or2" }

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
shadow = { id ="com.github.johnrengelman.shadow", version = "8.1.1"}
