[gamevals.tables]
herblore_unfinished=1230
herblore_finished=1231
herblore_cleaning=1232
herblore_barbarian_mixes=1233
herblore_swamp_tar=1234
herblore_crushing=1235

[gamevals.dbrows]
herblore_guam_unfinished=98119
herblore_marrentill_unfinished=98120
herblore_tarromin_unfinished=98121
herblore_harralander_unfinished=98122
herblore_ranarr_unfinished=98123
herblore_toadflax_unfinished=98124
herblore_irit_unfinished=98125
herblore_avantoe_unfinished=98126
herblore_kwuarm_unfinished=98127
herblore_snapdragon_unfinished=98128
herblore_cadantine_unfinished=98129
herblore_lantadyme_unfinished=98130
herblore_dwarf_weed_unfinished=98131
herblore_torstol_unfinished=98132
herblore_attack_potion=98133
herblore_antipoison=98134
herblore_strength_potion=98135
herblore_restore_potion=98136
herblore_energy_potion=98137
herblore_prayer_potion=98138
herblore_super_attack=98139
herblore_superantipoison=98140
herblore_fishing_potion=98141
herblore_super_energy=98142
herblore_super_strength=98143
herblore_weapon_poison=98144
herblore_super_restore=98145
herblore_super_defence=98146
herblore_antifire=98147
herblore_ranging_potion=98148
herblore_magic_potion=98149
herblore_zamorak_brew=98150
herblore_saradomin_brew=98151
herblore_defence_potion=98152
herblore_agility_potion=98153
herblore_combat_potion=98154
herblore_super_combat_potion=98158
herblore_clean_guam=98159
herblore_clean_marrentill=98160
herblore_clean_tarromin=98161
herblore_clean_harralander=98162
herblore_clean_ranarr=98163
herblore_clean_toadflax=98164
herblore_clean_irit=98165
herblore_clean_avantoe=98166
herblore_clean_kwuarm=98167
herblore_clean_snapdragon=98168
herblore_clean_cadantine=98169
herblore_clean_lantadyme=98170
herblore_clean_dwarf_weed=98171
herblore_clean_torstol=98172
herblore_attack_mix=98173
herblore_antipoison_mix=98174
herblore_strength_mix=98175
herblore_stat_restore_mix=98176
herblore_energy_mix=98177
herblore_defence_mix=98178
herblore_agility_mix=98179
herblore_prayer_mix=98180
herblore_super_attack_mix=98181
herblore_super_antipoison_mix=98182
herblore_fishing_mix=98183
herblore_super_energy_mix=98184
herblore_super_strength_mix=98185
herblore_super_restore_mix=98187
herblore_super_defence_mix=98188
herblore_antifire_mix=98189
herblore_ranging_mix=98190
herblore_magic_mix=98191
herblore_zamorak_mix=98192
herblore_hunter_potion=98193
herblore_bastion_potion=98194
herblore_battlemage_potion=98195
herblore_super_antifire=98196
herblore_extended_antivenom_plus=98197
herblore_attack_mix_caviar=98198
herblore_guam_tar=98199
herblore_marrentill_tar=98200
herblore_tarromin_tar=98201
herblore_harralander_tar=98202
herblore_irit_tar=98203
herblore_crush_bird_nest=98204
herblore_crush_chocolate=98205
herblore_crush_unicorn_horn=98206
herblore_crush_dragon_scale=98207
herblore_crush_goat_horn=98208
herblore_crush_superior_dragon_bones=98209