[gamevals.tables]
runecrafting_runes=1215
runecrafting_altars=1216
runecrafting_tiara=1217

[gamevals.dbrows]
runecrafting_rune_air=96784
runecrafting_rune_mind=96785
runecrafting_rune_water=96786
runecrafting_rune_earth=96787
runecrafting_rune_fire=96788
runecrafting_rune_body=96789
runecrafting_rune_cosmic=96790
runecrafting_rune_chaos=96791
runecrafting_rune_nature=96792
runecrafting_rune_law=96793
runecrafting_rune_death=96794
runecrafting_rune_wrath=96795
runecrafting_rune_soul=96796
runecrafting_rune_blood=96797
runecrafting_rune_astral=96798
runecrafting_altar_astral=96799
runecrafting_altar_blood=96800
runecrafting_altar_soul=96801
runecrafting_altar_wrath=96802
runecrafting_altar_death=96803
runecrafting_altar_law=96804
runecrafting_altar_nature=96805
runecrafting_altar_chaos=96806
runecrafting_altar_cosmic=96807
runecrafting_altar_body=96808
runecrafting_altar_fire=96809
runecrafting_altar_earth=96810
runecrafting_altar_water=96811
runecrafting_altar_mind=96812
runecrafting_altar_air=96813
runecrafting_tiara_wrath=96814
runecrafting_tiara_death=96815
runecrafting_tiara_law=96816
runecrafting_tiara_nature=96817
runecrafting_tiara_chaos=96818
runecrafting_tiara_cosmic=96819
runecrafting_tiara_body=96820
runecrafting_tiara_fire=96821
runecrafting_tiara_earth=96822
runecrafting_tiara_water=96823
runecrafting_tiara_mind=96824
runecrafting_tiara_air=96825