[gamevals.tables]
woodcutting_trees=1228
woodcutting_axes=1229

[gamevals.dbrows]
woodcutting_3a_axe_2h=96826
woodcutting_dragon_axe_2h=96827
woodcutting_rune_axe_2h=96828
woodcutting_adamant_axe_2h=96829
woodcutting_mithril_axe_2h=96830
woodcutting_steel_axe_2h=96831
woodcutting_iron_axe_2h=96832
woodcutting_bronze_axe_2h=96833
woodcutting_crystal_axe=96834
woodcutting_infernal_axe=96835
woodcutting_3a_axe=96836
woodcutting_dragon_axe=96837
woodcutting_rune_axe=96838
woodcutting_adamant_axe=96839
woodcutting_mithril_axe=96840
woodcutting_steel_axe=96841
woodcutting_iron_axe=96842
woodcutting_bronze_axe=96843

woodcutting_regular_tree=98109
woodcutting_oak_tree=98110
woodcutting_willow_tree=98111
woodcutting_teak_tree=98112
woodcutting_juniper_tree=98113
woodcutting_maple_tree=98114
woodcutting_mahogany_tree=98115
woodcutting_yew_tree=98116
woodcutting_magic_tree=98117
woodcutting_blisterwood_tree=98118