[gamevals.tables]
skill_prayer=1226

[gamevals.dbrows]
infernalashes=97002
abyssalashes=97003
maliciousashes=97004
vileashes=97005
fiendishashes=97006
beardedgorillabones=97007
gorillabones=97008
mediumninjamonkeybones=97009
smallninjamonkeybones=97010
largezombiemonkeybones=97011
smallzombiemonkeybones=97012
bleachedbones=97013
bonesapeatoll=97014
alansbones=97015
superiordragonbones=97016
ourgbones=97017
dagannothbones=97018
hydrabones=97019
raurgbones=97020
lavadragonbones=97021
fayrgbones=97022
drakebones=97023
dragonbones=97024
wyvernbones=97025
wyrmbones=97026
babydragonbones=97027
shaikahanbones=97028
zogrebones=97029
wyrmlingbones=97030
jogrebones=97031
bigbones=97032
batbones=97033
monkeybones=97034
burntbones=97035
wolfbones=97036
bones=97037