[gamevals.tables]
skill_thieving_pickpocketing=1236

[gamevals.dbrows]
man=97038
woman=97039
man_drops=97040
farmer=97041
farmer_drops=97042
male_ham_member=97043
female_ham_member=97044
ham_member_drops=97045
al_kharid_warrior=97046
warrior=97047
warrior_drops=97048
rogue=97049
rogue_drops=97050
cave_goblin=97051
cave_goblin_drops=97052
master_farmer=97053
master_farmer_drops=97054
guard=97055
guard_drops=97056
menaphite_thug=97057
menaphite_thug_drops=97058
knight_of_ardougne=97059
knight_of_varlamore=97060
knight_of_ardougne_drops=97061
paladin=97062
paladin_drops=97063
gnome=97064
gnome_drops=97065
hero=97066
hero_drops=97067
elf=97068
elf_drops=97069
desert_bandit=97070
desert_bandit_drops=97071
fremennik_citizen=97072
fremennik_citizen_drops=97073
vyre=97074
vyre_drops=97075
yanille_watchman=97076
yanille_watchman_drops=97077
bearded_pollnivnian_bandit=97078
bearded_pollnivnian_bandit_drops=97079
pollnivnian_bandit=97080
pollnivnian_bandit_drops=97081
digsite_workman=97082
digsite_workman_drops=97083
villager=97084
villager_drops=97085
wealthy_citizen=97086
wealthy_citizen_drops=97087
tzhaar=97088
tzhaar_drops=97089