[gamevals.tables]
stat_components=1225

[gamevals.dbrows]
firemaking_stat=9692
attack_stat=96943
crafting_stat=96944
fletching_stat=96945
hunter_stat=96946
magic_stat=96947
strength_stat=96948
ranged_stat=96949
farming_stat=96950
woodcutting_stat=96952
cooking_stat=96953
fishing_stat=96954
smithing_stat=96955
mining_stat=96956
prayer_stat=96957
slayer_stat=96958
hitpoints_stat=96959
defence_stat=96960
thieving_stat=96961
herblore_stat=96962
agility_stat=96963
construction_stat=96964
runecraft_stat=96965
sailing_stat=96966